
CREATE TABLE product_descriptions (
    id SERIAL PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT,
    base_price DECIMAL(10,2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD'
);

INSERT INTO product_descriptions (id, name, category, description, base_price, currency) VALUES
(1, 'Wireless Bluetooth Headphones', 'Electronics', 'Premium noise-cancelling wireless headphones with 30-hour battery life', 89.99, 'USD'),
(2, 'Smart Fitness Watch', 'Electronics', 'Advanced fitness tracker with heart rate monitoring and GPS', 299.99, 'USD'),
(3, 'Portable Bluetooth Speaker', 'Electronics', 'Waterproof portable speaker with 360-degree sound', 356.25, 'USD'),
(4, '4K Webcam', 'Electronics', 'Ultra HD webcam with auto-focus and noise reduction', 367.25, 'USD'),
(5, 'Wireless Charging Pad', 'Electronics', 'Fast wireless charger compatible with all Qi-enabled devices', 423.75, 'USD'),
(6, 'Gaming Mechanical Keyboard', 'Electronics', 'RGB backlit mechanical keyboard with blue switches', 345.60, 'USD'),
(7, 'Ergonomic Wireless Mouse', 'Electronics', 'Precision wireless mouse with ergonomic design', 189.99, 'USD'),
(8, 'Tablet Stand Adjustable', 'Electronics', 'Universal adjustable stand for tablets and phones', 299.99, 'USD'),
(9, 'USB-C Hub 7-in-1', 'Electronics', 'Multi-port hub with HDMI, USB 3.0, and SD card slots', 456.80, 'USD'),
(10, 'Smartphone Camera Lens Kit', 'Electronics', '3-in-1 lens kit with wide-angle, macro, and fisheye lenses', 423.55, 'USD'),

(11, 'Organic Cotton T-Shirt', 'Clothing', 'Soft organic cotton t-shirt available in multiple colors', 289.45, 'USD'),
(12, 'Denim Jacket Classic', 'Clothing', 'Timeless denim jacket with vintage wash finish', 72.91, 'USD'),
(13, 'Running Shorts Athletic', 'Clothing', 'Lightweight athletic shorts with moisture-wicking fabric', 298.75, 'USD'),
(14, 'Wool Blend Sweater', 'Clothing', 'Cozy wool blend sweater perfect for cold weather', 89.25, 'USD'),
(15, 'Leather Ankle Boots', 'Clothing', 'Genuine leather ankle boots with comfortable sole', 78.25, 'USD'),
(16, 'Cotton Hoodie Pullover', 'Clothing', 'Comfortable cotton hoodie with kangaroo pocket', 278.90, 'USD'),
(17, 'Silk Scarf Luxury', 'Clothing', 'Premium silk scarf with elegant pattern design', 367.25, 'USD'),
(18, 'Athletic Leggings', 'Clothing', 'High-waisted leggings with compression fit', 267.40, 'USD'),
(19, 'Casual Button-Down Shirt', 'Clothing', 'Versatile button-down shirt suitable for work or casual wear', 199.99, 'USD'),
(20, 'Winter Puffer Jacket', 'Clothing', 'Insulated puffer jacket with water-resistant coating', 298.70, 'USD'),

(21, 'The Art of Data Science', 'Books', 'Comprehensive guide to modern data science techniques and applications', 298.45, 'USD'),
(22, 'Mindfulness and Meditation', 'Books', 'Practical guide to incorporating mindfulness into daily life', 77.31, 'USD'),
(23, 'Cooking Around the World', 'Books', 'International cookbook with recipes from 50 countries', 234.75, 'USD'),
(24, 'Digital Photography Mastery', 'Books', 'Complete guide to digital photography for beginners and professionals', 234.85, 'USD'),
(25, 'Sustainable Living Guide', 'Books', 'Practical tips for eco-friendly living and reducing environmental impact', 234.50, 'USD'),
(26, 'Financial Planning Basics', 'Books', 'Essential guide to personal finance and investment strategies', 189.95, 'USD'),
(27, 'Creative Writing Workshop', 'Books', 'Exercises and techniques for improving creative writing skills', 89.45, 'USD'),
(28, 'Home Gardening Encyclopedia', 'Books', 'Complete guide to growing vegetables, herbs, and flowers at home', 98.76, 'USD'),
(29, 'Machine Learning Fundamentals', 'Books', 'Introduction to machine learning concepts and algorithms', 245.90, 'USD'),
(30, 'Travel Photography Tips', 'Books', 'Professional techniques for capturing stunning travel photos', 278.95, 'USD'),

(31, 'Ceramic Plant Pot Set', 'Home & Garden', 'Set of 3 decorative ceramic pots with drainage holes', 278.60, 'USD'),
(32, 'LED String Lights', 'Home & Garden', 'Warm white LED string lights perfect for indoor and outdoor use', 298.55, 'USD'),
(33, 'Bamboo Cutting Board', 'Home & Garden', 'Eco-friendly bamboo cutting board with juice groove', 156.80, 'USD'),
(34, 'Essential Oil Diffuser', 'Home & Garden', 'Ultrasonic aromatherapy diffuser with color-changing LED', 123.45, 'USD'),
(35, 'Memory Foam Pillow', 'Home & Garden', 'Contoured memory foam pillow for better sleep support', 234.90, 'USD'),
(36, 'Stainless Steel Water Bottle', 'Home & Garden', 'Insulated water bottle that keeps drinks cold for 24 hours', 48.57, 'USD'),
(37, 'Microfiber Cleaning Cloths', 'Home & Garden', 'Pack of 12 ultra-soft microfiber cleaning cloths', 72.95, 'USD'),
(38, 'Solar Garden Lights', 'Home & Garden', 'Set of 8 solar-powered LED garden pathway lights', 34.99, 'USD'),
(39, 'Non-Stick Cookware Set', 'Home & Garden', '10-piece non-stick cookware set with heat-resistant handles', 78.45, 'USD'),
(40, 'Throw Blanket Cozy', 'Home & Garden', 'Ultra-soft fleece throw blanket perfect for couch or bed', 34.99, 'USD'),

(41, 'Yoga Mat Premium', 'Sports & Outdoors', 'Non-slip yoga mat with extra cushioning and carrying strap', 48.60, 'USD'),
(42, 'Camping Sleeping Bag', 'Sports & Outdoors', 'Lightweight sleeping bag rated for 3-season camping', 79.99, 'USD'),
(43, 'Resistance Bands Set', 'Sports & Outdoors', 'Set of 5 resistance bands with different resistance levels', 48.60, 'USD'),
(44, 'Hiking Backpack 40L', 'Sports & Outdoors', 'Durable hiking backpack with multiple compartments', 99.53, 'USD'),
(45, 'Water Sports Goggles', 'Sports & Outdoors', 'Anti-fog swimming goggles with UV protection', 22.42, 'USD'),
(46, 'Portable Camping Chair', 'Sports & Outdoors', 'Lightweight folding chair perfect for camping and outdoor events', 44.99, 'USD'),
(47, 'Tennis Racket Professional', 'Sports & Outdoors', 'Professional-grade tennis racket with graphite frame', 63.15, 'USD'),
(48, 'Bike Helmet Safety', 'Sports & Outdoors', 'Lightweight bike helmet with adjustable fit system', 63.15, 'USD'),
(49, 'Fishing Rod Combo', 'Sports & Outdoors', 'Complete fishing rod and reel combo for beginners', 94.95, 'USD'),
(50, 'Running Armband Phone', 'Sports & Outdoors', 'Adjustable armband for smartphones during workouts', 94.88, 'USD'),

(51, 'Organic Face Moisturizer', 'Beauty & Personal Care', 'Natural face moisturizer with hyaluronic acid and vitamin E', 34.99, 'USD'),
(52, 'Electric Toothbrush', 'Beauty & Personal Care', 'Rechargeable electric toothbrush with multiple cleaning modes', 356.75, 'USD'),
(53, 'Hair Styling Tool Set', 'Beauty & Personal Care', '3-in-1 hair styling tool with curling, straightening, and wave functions', 423.40, 'USD'),
(54, 'Vitamin C Serum', 'Beauty & Personal Care', 'Anti-aging vitamin C serum for brighter, smoother skin', 24.99, 'USD'),
(55, 'Makeup Brush Set', 'Beauty & Personal Care', 'Professional makeup brush set with 12 brushes and carrying case', 94.85, 'USD'),
(56, 'Beard Grooming Kit', 'Beauty & Personal Care', 'Complete beard care kit with oil, balm, and wooden comb', 94.80, 'USD'),
(57, 'Nail Care Set', 'Beauty & Personal Care', 'Professional nail care set with files, clippers, and cuticle tools', 19.99, 'USD'),
(58, 'Body Lotion Luxury', 'Beauty & Personal Care', 'Moisturizing body lotion with shea butter and natural oils', 99.30, 'USD'),
(59, 'Facial Cleansing Brush', 'Beauty & Personal Care', 'Sonic facial cleansing brush for deep pore cleaning', 139.20, 'USD'),
(60, 'Hair Mask Treatment', 'Beauty & Personal Care', 'Deep conditioning hair mask for damaged and dry hair', 94.95, 'USD'),

(61, 'Building Blocks Creative Set', 'Toys & Games', 'Educational building blocks set for developing creativity and motor skills', 34.99, 'USD'),
(62, 'Board Game Strategy', 'Toys & Games', 'Award-winning strategy board game for 2-4 players', 44.99, 'USD'),
(63, 'Remote Control Drone', 'Toys & Games', 'Easy-to-fly drone with HD camera and smartphone control', 99.99, 'USD'),
(64, 'Puzzle 1000 Pieces', 'Toys & Games', 'Challenging 1000-piece jigsaw puzzle with beautiful landscape image', 23.71, 'USD'),
(65, 'Art Supplies Kit Kids', 'Toys & Games', 'Complete art kit with crayons, markers, colored pencils, and paper', 29.99, 'USD'),
(66, 'Science Experiment Kit', 'Toys & Games', 'Educational science kit with 20+ safe experiments for kids', 39.99, 'USD'),
(67, 'Musical Keyboard Mini', 'Toys & Games', '37-key mini keyboard with built-in songs and learning modes', 19.73, 'USD'),
(68, 'Action Figure Collectible', 'Toys & Games', 'Highly detailed action figure with multiple points of articulation', 20.63, 'USD'),
(69, 'Card Game Family Fun', 'Toys & Games', 'Fast-paced card game perfect for family game nights', 37.96, 'USD'),
(70, 'Educational Tablet Kids', 'Toys & Games', 'Kid-friendly tablet with educational games and parental controls', 79.99, 'USD'),

(71, 'Car Phone Mount', 'Automotive', 'Universal car phone mount with 360-degree rotation', 41.96, 'USD'),
(72, 'Tire Pressure Gauge', 'Automotive', 'Digital tire pressure gauge with LED display', 24.99, 'USD'),
(73, 'Car Air Freshener Set', 'Automotive', 'Long-lasting car air fresheners in assorted scents', 46.96, 'USD'),
(74, 'Emergency Car Kit', 'Automotive', 'Complete emergency kit with jumper cables, flashlight, and tools', 17.69, 'USD'),
(75, 'Dashboard Camera HD', 'Automotive', 'Full HD dashboard camera with night vision and loop recording', 39.11, 'USD'),
(76, 'Car Seat Organizer', 'Automotive', 'Multi-pocket seat organizer for storing car essentials', 22.45, 'USD'),
(77, 'Bluetooth Car Adapter', 'Automotive', 'Wireless Bluetooth adapter for hands-free calling and music', 41.98, 'USD'),
(78, 'Car Cleaning Kit', 'Automotive', 'Complete car cleaning kit with microfiber cloths and cleaning solutions', 39.21, 'USD'),
(79, 'Sunshade Windshield', 'Automotive', 'Reflective windshield sunshade for UV protection and cooling', 16.99, 'USD'),
(80, 'Car Floor Mats', 'Automotive', 'All-weather rubber floor mats for maximum protection', 49.99, 'USD'),

(81, 'Dog Toy Rope', 'Pet Supplies', 'Durable rope toy for dogs with natural cotton fibers', 19.59, 'USD'),
(82, 'Cat Scratching Post', 'Pet Supplies', 'Tall scratching post with sisal rope and hanging toys', 17.68, 'USD'),
(83, 'Pet Food Bowl Set', 'Pet Supplies', 'Stainless steel food and water bowl set with non-slip base', 16.19, 'USD'),
(84, 'Dog Leash Retractable', 'Pet Supplies', 'Retractable dog leash with comfortable grip handle', 19.99, 'USD'),
(85, 'Cat Litter Mat', 'Pet Supplies', 'Large litter mat that traps litter and protects floors', 17.43, 'USD'),
(86, 'Pet Carrier Soft', 'Pet Supplies', 'Soft-sided pet carrier approved for airline travel', 16.77, 'USD'),
(87, 'Dog Training Treats', 'Pet Supplies', 'Natural training treats made with real chicken and vegetables', 15.49, 'USD'),
(88, 'Pet Grooming Brush', 'Pet Supplies', 'Self-cleaning pet brush for removing loose fur and tangles', 22.99, 'USD'),
(89, 'Automatic Pet Feeder', 'Pet Supplies', 'Programmable automatic feeder with portion control', 17.99, 'USD'),
(90, 'Pet Bed Orthopedic', 'Pet Supplies', 'Memory foam pet bed with removable washable cover', 69.99, 'USD'),

(91, 'Desk Organizer Bamboo', 'Office Supplies', 'Eco-friendly bamboo desk organizer with multiple compartments', 34.99, 'USD'),
(92, 'Ergonomic Office Chair', 'Office Supplies', 'Adjustable office chair with lumbar support and breathable mesh', 199.99, 'USD'),
(93, 'Standing Desk Converter', 'Office Supplies', 'Height-adjustable desk converter for healthier working', 149.99, 'USD'),
(94, 'Wireless Presenter Remote', 'Office Supplies', 'Laser pointer and presentation remote with USB receiver', 29.99, 'USD'),
(95, 'Document Shredder', 'Office Supplies', 'Cross-cut paper shredder for secure document disposal', 89.99, 'USD'),
(96, 'Whiteboard Magnetic', 'Office Supplies', 'Large magnetic whiteboard with aluminum frame and marker tray', 79.99, 'USD'),
(97, 'Printer Paper Premium', 'Office Supplies', 'High-quality multipurpose printer paper, 500 sheets', 24.99, 'USD'),
(98, 'Stapler Heavy Duty', 'Office Supplies', 'Heavy-duty stapler that can handle up to 100 sheets', 34.99, 'USD'),
(99, 'File Cabinet 4-Drawer', 'Office Supplies', 'Locking 4-drawer file cabinet for letter-size documents', 299.99, 'USD'),
(100, 'Desk Lamp LED', 'Office Supplies', 'Adjustable LED desk lamp with USB charging port', 49.99, 'USD');

CREATE INDEX idx_product_descriptions_category ON product_descriptions(category);
CREATE INDEX idx_product_descriptions_price ON product_descriptions(base_price);
